/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.Equipamento;
import dao.EquipamentoDAO;
import java.awt.EventQueue;
import java.awt.HeadlessException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import pesquisas.PesquisaBairro;
import pesquisas.PesquisaMunicipio;
import pesquisas.PesquisaUF;

import util.Utilitarios;

/**
 *
 * @author Leo
 */
public class JanelaEquipamento extends javax.swing.JInternalFrame {

    private int idBairroSelecionado;
    private int idMunicipioSelecionado;
    private int idUFSelecionada;
    private int idEquipSelecionado;
    private boolean removendo = false;
    private List<Equipamento> lista;
    private DefaultTableModel modelo;
    private char operacao;

    public JanelaEquipamento() {

        initComponents();

        modelo = (DefaultTableModel) tbEquipamento.getModel();
        tbEquipamento.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION);

        tbEquipamento.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {
                    linhaSelecionada();
                }
            }
        });
        atualizarTabela(); //carregar tabela ao abrir tela
    }

    public void linhaSelecionada() {
        if (!removendo) {

            txtDescricao.setText(lista.get(tbEquipamento.getSelectedRow()).getDescricao());
            txtModelo.setText(lista.get(tbEquipamento.getSelectedRow()).getModelo());
            txtMarca.setText(lista.get(tbEquipamento.getSelectedRow()).getMarca());
            //data instaçacao
            //data retirada
            txtEndereco.setText(lista.get(tbEquipamento.getSelectedRow()).getEndereco());
            txtBairro.setText(lista.get(tbEquipamento.getSelectedRow()).getBairro());
            // txtUF.setText(lista.get(tbEquipamento.getSelectedRow()).get());
            txtLatitude.setText(lista.get(tbEquipamento.getSelectedRow()).getLatitude());
            txtLongitude.setText(lista.get(tbEquipamento.getSelectedRow()).getLongitude());

        }
    }

    public void atualizarTabela() {
        EquipamentoDAO dao = new EquipamentoDAO();
        lista = dao.listarEquipamento();

        removendo = true;
        modelo.getDataVector().removeAllElements();

        for (Equipamento eq : lista) {
            modelo.addRow(new Object[]{
                eq.getIdequipamento(),
                eq.getDescricao(),
                eq.getBairro(),
                eq.getLatitude(),
                eq.getLongitude(),});
        }

        removendo = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbEquipamento = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnPesquisaBairro = new javax.swing.JButton();
        txtUF = new javax.swing.JTextField();
        btnPesquisaUF = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        btnPesquisaCidade = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        btnExibeLocal = new javax.swing.JButton();
        txtDataInstalacao = new javax.swing.JFormattedTextField();
        txtDataRetirada = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Equipamento");

        tbEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idEquip", "Descrição", "Bairro", "Latitude", "Longitude"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbEquipamento);
        if (tbEquipamento.getColumnModel().getColumnCount() > 0) {
            tbEquipamento.getColumnModel().getColumn(0).setResizable(false);
            tbEquipamento.getColumnModel().getColumn(1).setResizable(false);
            tbEquipamento.getColumnModel().getColumn(2).setResizable(false);
            tbEquipamento.getColumnModel().getColumn(3).setResizable(false);
            tbEquipamento.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Descrição do Equipamento");

        jLabel2.setText("Modelo");

        jLabel3.setText("Marca");

        jLabel4.setText("Data de Instalação");

        jLabel5.setText("Endereço");

        jLabel6.setText("Data de Retirada");

        jLabel7.setText("Bairro");

        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado");

        btnPesquisaBairro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\pesquisar_icone.png")); // NOI18N
        btnPesquisaBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaBairroActionPerformed(evt);
            }
        });

        btnPesquisaUF.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\pesquisar_icone.png")); // NOI18N
        btnPesquisaUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaUFActionPerformed(evt);
            }
        });

        jLabel9.setText("Cidade");

        btnPesquisaCidade.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\pesquisar_icone.png")); // NOI18N
        btnPesquisaCidade.setToolTipText("");
        btnPesquisaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCidadeActionPerformed(evt);
            }
        });

        jLabel10.setText("Latitude");

        jLabel11.setText("Longitude");

        btnExibeLocal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\maps_icone.png")); // NOI18N
        btnExibeLocal.setText("Exibir Localização");
        btnExibeLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibeLocalActionPerformed(evt);
            }
        });

        try {
            txtDataInstalacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataRetirada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaUF)
                        .addGap(18, 18, 18)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisaCidade)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDescricao)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExibeLocal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(153, 153, 153)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtDataInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(43, 43, 43))
                                    .addComponent(txtDataRetirada)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisaBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaUF)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBairro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExibeLocal)
                        .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        btnNovo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\novo_icone.png")); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNovo);

        btnSalvar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\salvar_icone.png")); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalvar);

        btnAlterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\editar_icone.png")); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAlterar);

        btnExcluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\excluir_icone.png")); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluir);

        btnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\cancelar_icone.png")); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        btnPrimeiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\primeiro_icone.png")); // NOI18N
        btnPrimeiro.setToolTipText("Primeiro Registro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrimeiro);

        btnAnterior.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\anterior_icone.png")); // NOI18N
        btnAnterior.setToolTipText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnterior);

        btnProximo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\proximo_icone.png")); // NOI18N
        btnProximo.setToolTipText("Proximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        jPanel3.add(btnProximo);

        btnUltimo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leo\\Documents\\NetBeansProjects\\TCC\\imagens\\ultimo_icone.png")); // NOI18N
        btnUltimo.setToolTipText("Ultimo Registro");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        jPanel3.add(btnUltimo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        operacao = 'I';

        Utilitarios.habilitaDesabilita(jPanel1, true);
        Utilitarios.limpaCampos(jPanel1);
        btnNovo.setEnabled(false);
        txtDescricao.requestFocus();
        tbEquipamento.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String dataString = txtDataInstalacao.getText();
        DateFormat ft = new SimpleDateFormat("dd/MM/yyyy");
        java.sql.Date datainstalacao = null;
        try {
            datainstalacao = new java.sql.Date(ft.parse(dataString).getTime());
        } catch (ParseException ex) {
            Logger.getLogger(JanelaEquipamento.class.getName()).log(Level.SEVERE, null, ex);
        }

        String dataString2 = txtDataRetirada.getText();
        DateFormat ft2 = new SimpleDateFormat("dd/MM/yyyy");
        java.sql.Date dataretirada = null;
        try {
            dataretirada = new java.sql.Date(ft2.parse(dataString).getTime());
        } catch (ParseException ex) {
            Logger.getLogger(JanelaEquipamento.class.getName()).log(Level.SEVERE, null, ex);
        }

        Equipamento eq = new Equipamento();

        eq.setDescricao(txtDescricao.getText());
        eq.setModelo(txtModelo.getText());
        eq.setMarca(txtMarca.getText());
        eq.setDatainstalacao(datainstalacao);
        eq.setDataretirada(dataretirada);
        eq.setLatitude(txtLatitude.getText());
        eq.setLongitude(txtLongitude.getText());
        eq.setIdmunicipio(idMunicipioSelecionado);
        eq.setIdbairro(idBairroSelecionado);
        eq.setEndereco(txtEndereco.getText());

        EquipamentoDAO dao = new EquipamentoDAO();

        switch (operacao) {
            case 'I':
                if (dao.insereEquipamento(eq)) {
                    camposOperacao();
                }
                break;
            case 'A':
                eq.setIdequipamento(idEquipSelecionado);
                if (dao.alteraEquipamento(eq)) {
                    camposOperacao();
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Erro");
        }
        atualizarTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        operacao = 'A';
        idEquipSelecionado = (lista.get(tbEquipamento.getSelectedRow()).getIdequipamento());
        System.out.println("equipamento selecionado" + idEquipSelecionado);
        Utilitarios.habilitaDesabilita(jPanel1, true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int idusuario = lista.get(tbEquipamento.getSelectedRow()).getIdequipamento();
        new EquipamentoDAO().excluirEquipamento(idusuario);
        atualizarTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Utilitarios.habilitaDesabilita(jPanel1, false);
        Utilitarios.limpaCampos(jPanel1);
        btnNovo.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tbEquipamento.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        Utilitarios.primeiro(tbEquipamento);
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        Utilitarios.anterior(tbEquipamento);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        Utilitarios.proximo(tbEquipamento);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        Utilitarios.ultimo(tbEquipamento);
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPesquisaBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaBairroActionPerformed
        PesquisaBairro pesquisa = new PesquisaBairro(null, true);
        pesquisa.setVisible(true);

        if (pesquisa.selecionou) {
            txtBairro.setText(pesquisa.lista.get(
                    pesquisa.getLinhaSelecionada()).getNome());
            idBairroSelecionado
                    = pesquisa.lista.get(
                            pesquisa.getLinhaSelecionada()).getIdbairro();
        }
    }//GEN-LAST:event_btnPesquisaBairroActionPerformed

    private void btnPesquisaUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaUFActionPerformed
        PesquisaUF pesquisaUF = new PesquisaUF(null, true);
        pesquisaUF.setVisible(true);

        if (pesquisaUF.selecionou) {
            txtUF.setText(pesquisaUF.lista.get(
                    pesquisaUF.getLinhaSelecionada()).getNome());
            idUFSelecionada
                    = pesquisaUF.lista.get(
                            pesquisaUF.getLinhaSelecionada()).getIdunidade_federacao();
        }


    }//GEN-LAST:event_btnPesquisaUFActionPerformed

    private void btnPesquisaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCidadeActionPerformed
        PesquisaMunicipio pesquisa = new PesquisaMunicipio(null, true, idUFSelecionada);
        pesquisa.setVisible(true);

        if (pesquisa.selecionou) {
            txtCidade.setText(pesquisa.lista.get(
                    pesquisa.getLinhaSelecionada()).getNome());
            idMunicipioSelecionado
                    = pesquisa.lista.get(
                            pesquisa.getLinhaSelecionada()).getIdmunicipio();
        }
    }//GEN-LAST:event_btnPesquisaCidadeActionPerformed

    private void btnExibeLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibeLocalActionPerformed
//AIzaSyBs8xS8mvbgQU0GMneqIIQbQH8KkNlh9oE - api google maps

        try {
            try {
                java.awt.Desktop.getDesktop().browse(new java.net.URI("http://localhost/TCC/index.php?latitude=" + lista.get(tbEquipamento.getSelectedRow()).getLatitude() + "&longitude=" + lista.get(tbEquipamento.getSelectedRow()).getLongitude() + ""));
            } catch (URISyntaxException ex) {
                // Logger.getLogger(MenuLinks.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            // Logger.getLogger(MenuLinks.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnExibeLocalActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExibeLocal;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaBairro;
    private javax.swing.JButton btnPesquisaCidade;
    private javax.swing.JButton btnPesquisaUF;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEquipamento;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtDataInstalacao;
    private javax.swing.JFormattedTextField txtDataRetirada;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables
private void camposOperacao() throws HeadlessException {
        Utilitarios.habilitaDesabilita(jPanel1, false);
        btnNovo.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        tbEquipamento.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);

        JOptionPane.showMessageDialog(this, "Sucesso.");
    }

}
